/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

import {
  LwLayoutPage, 
  LwAdaptivePage,
  LwLayoutPageItem,
  LwForm,
  LwButton,
  lwTimerButton,
  LwRadio,
  LwSelect,
  LwSelectTable,
  LwTable,
  LwTabs,
  LwStepWizard,
  LwModuleForm,
  LwQueryCondition,
  LwCheckBox,
  LwChart,
  LwDetail
} from  "./src/index"

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    LwAdaptivePage: typeof LwAdaptivePage
    LwLayoutPage: typeof LwLayoutPage;
    LwLayoutPageItem: typeof LwLayoutPageItem
    LwForm: typeof LwForm
    LwButton: typeof LwButton
    lwTimerButton: typeof lwTimerButton
    LwRadio: typeof LwRadio
    LwSelect: typeof LwSelect;
    LwSelectTable: typeof LwSelectTable
    LwTable: typeof LwTable
    LwTabs: typeof LwTabs
    LwStepWizard: typeof LwStepWizard
    LwModuleForm: typeof LwModuleForm
    LwQueryCondition: typeof LwQueryCondition
    LwCheckBox: typeof LwCheckBox
    LwChart: typeof LwChart
    LwDetail: typeof LwDetail
  }
}
